# Netlify Configuration for Payro.cz Next.js App

[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

# Next.js plugin for Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables to set in Netlify Dashboard:
# NEXT_PUBLIC_SUPABASE_URL = your_supabase_url
# NEXT_PUBLIC_SUPABASE_ANON_KEY = your_supabase_anon_key
# NEXT_PUBLIC_APP_URL = https://your-domain.netlify.app

